### ISSUE TITLE
Strange config error

### ISSUE THREAD

**Issue by TomTheHero** [astei/SuperbVote#57]
I'm unable to get the config to load and the error makes no sense.

13.08 10:31:45 [Server] ERROR Cannot load plugins/SuperbVote/config.yml
13.08 10:31:45 [Server] INFO org.bukkit.configuration.InvalidConfigurationException: while parsing a block collection
13.08 10:31:45 [Server] INFO in "<string>", line 33, column 5:
13.08 10:31:45 [Server] INFO - if:
13.08 10:31:45 [Server] INFO ^
13.08 10:31:45 [Server] INFO expected <block end>, but found Key
13.08 10:31:45 [Server] INFO in "<string>", line 34, column 5:
13.08 10:31:45 [Server] INFO chance-percentage: 8
13.08 10:31:45 [Server] INFO ^

https://cdn.discordapp.com/attachments/409536936638808084/478571986168315914/config.yml

**Comment by astei** [comment]
Your configuration is indented incorrectly. i.e.

```yaml
rewards:
  # Example of matchers.
    - if:
    chance-percentage: 8
    commands:
    - give %player% 357 64
    player-message: "&aYour random reward for voting is: 64 Cookies"
    broadcast-message: "&a %player% has voted for the server and was awarded 64 Cookies"
        - if:
    chance-percentage: 1
    commands:
    - give %player% 5023 1 8
    player-message: "&aYour random reward for voting is: 1 AntiMatter Charge"
    broadcast-message: "&a %player% has voted for the server and was awarded 1 AntiMatter Charge"
```

versus the correct

```yaml
rewards:
  # Example of matchers.
  - if:
      chance-percentage: 8
    commands:
    - give %player% 357 64
    player-message: "&aYour random reward for voting is: 64 Cookies"
    broadcast-message: "&a %player% has voted for the server and was awarded 64 Cookies"
  - if:
      chance-percentage: 1
    commands:
    - give %player% 5023 1 8
    player-message: "&aYour random reward for voting is: 1 AntiMatter Charge"
    broadcast-message: "&a %player% has voted for the server and was awarded 1 AntiMatter Charge"
```

Please use http://yaml-online-parser.appspot.com/ to check your configuration for correct formatting
