### ISSUE TITLE
voting percentages

### ISSUE THREAD

**Issue by Alv5ro** [astei/SuperbVote#95]
Hey, I've looked in the wiki and obviously tried myself, I don't want to have the usual "you vote for a key" system, I want them to have the chance (33%) of winning it, and 67%chance of getting 10k. I gave myself the permissions as well. This is what I tried, and it obviously didn't work. Please note that the settings are temporary (it's not meant to be 50% for each, just for testing purposes).
```
rewards:
  # Example of matchers. See https://github.com/minecrafter/SuperbVote/wiki/Configuration#if for a full list of available
  # matchers.
  - if:
      permission: superbvote.10k
      chance-percentage: 50
      service: SpecialService
    commands:
    - eco give %player% 10000
    player-message: "&aThanks for voting, you have been rewarded with $10,000."
    #broadcast-message: "&a%player% got really lucky and was rewarded with $10000!"
  # A default reward is required. Default rewards are defined by using default: true as a matcher. No other matchers can
  # be used with this matcher and only one such reward can be the default reward.
  - if:
      permission: superbvote.20k
      chance-percentage: 50
      service: SpecialService
    commands:
    - eco give %player% 10000
    player-message: "&aThanks for voting, you have been rewarded with $10,000."
    #broadcast-message: "&a%player% got really lucky and was rewarded with $10000!"
  # A default reward is required. Default rewards are defined by using default: true as a matcher. No other matchers can
  # be used with this matcher and only one such reward can be the default reward.
  - if:
      default: false
    commands:
    - cc give physical vote 1 %player%
    broadcast-message: "&5&l%player% &7voted and recieved a &8[&c»&8]&a&lVOTE&8[&c«&8] &b&lKey"
    player-message: "&7Go to /warp crates to redeem"
```

**Comment by astei** [comment]
I bet you're not voting on the non-existent "SpecialService". Also, `default: false` makes no sense.

**Comment by Alv5ro** [comment]
Thanks for the help, I removed the special service section (as it isn't needed) and made default: true. However even though the default (a vote key) is at the bottom of the list, players seem to get that every time. This is the updated config.
```
rewards:
  # Example of matchers. See https://github.com/minecrafter/SuperbVote/wiki/Configuration#if for a full list of available
  # matchers.
  - if:
      permission: superbvote.10k
      chance-percentage: 34
      #service: SpecialService
    commands:
    - eco give %player% 10000
    player-message: "&aThanks for voting, you have been rewarded with $10,000."
    #broadcast-message: "&a%player% got really lucky and was rewarded with $10000!"
  # A default reward is required. Default rewards are defined by using default: true as a matcher. No other matchers can
  # be used with this matcher and only one such reward can be the default reward.
  - if:
      permission: superbvote.20k
      chance-percentage: 33
    commands:
    - eco give %player% 20000
    player-message: "&aThanks for voting, you have been rewarded with $20,000."
    #broadcast-message: "&a%player% got really lucky and was rewarded with $10000!"
  # A default reward is required. Default rewards are defined by using default: true as a matcher. No other matchers can
  # be used with this matcher and only one such reward can be the default reward.
  - if:
      permission: superbvote.key
      chance-percentage: 33
    commands:
    - cc give physical vote 1 %player%
    broadcast-message: "&5&l%player% &7voted and recieved a &8[&c»&8]&a&lVOTE&8[&c«&8] &b&lKey"
    player-message: "&7Go to /warp crates to redeem"
  - if:
      default: true
    commands:
    - cc give physical vote 1 %player%
    broadcast-message: "&5&l%player% &7voted and recieved a &8[&c»&8]&a&lVOTE&8[&c«&8] &b&lKey"
    player-message: "&7Go to /warp crates to redeem"
```
